/* eslint-disable */
// TODO: Remove previous line and work through linting issues at next edit

const RC = require('rc')('AZURELOG', require('../../../config/azurelog.config.json'));

// Set config object to be returned
const config = {
  TENANT_ID: RC.TENANT_ID,
  CLIENT_ID: RC.CLIENT_ID,
  CLIENT_SECRET: RC.CLIENT_SECRET,
  REDIRECT_URI: RC.REDIRECT_URI,
  RESOURCE: RC.RESOURCE,
  AUTH_TOKEN_ENDPOINT: RC.AUTH_TOKEN_ENDPOINT,
  WORKSPACE_ID: RC.WORKSPACE_ID,
  LOG_API_ENDPOINT: RC.LOG_API_ENDPOINT,
  SEARCH_QUERY_TEMPLATE: RC.SEARCH_QUERY_TEMPLATE,
  KAFKA_MESSAGE_PATTERN: RC.KAFKA_MESSAGE_PATTERN,
  CLEAN_MESSAGE_REPLACE_PATTERNS: RC.CLEAN_MESSAGE_REPLACE_PATTERNS,
  CLEAN_SIGNATURE_REPLACE_PATTERNS: RC.CLEAN_SIGNATURE_REPLACE_PATTERNS
};

module.exports = config;
